In [7]:
from alias_multinomial import AliasMethod
import torch

nLem = 100
unigrams = torch.ones(nLem)
multinomial = AliasMethod(unigrams)

In [8]:
for _ in range(10):
    print(multinomial.draw(5))

tensor([25, 16, 62, 92, 10])
tensor([23, 22, 41,  2, 58])
tensor([25, 81,  9, 24, 94])
tensor([58, 61, 72, 33, 59])
tensor([17, 41, 58, 94, 71])
tensor([88, 17, 57, 81, 92])
tensor([42, 49, 79, 41, 21])
tensor([68, 24, 98,  0, 72])
tensor([45, 55, 22, 74, 56])
tensor([43, 40,  8, 84, 56])
